FROM mysql:latest

LABEL maintainer="Johan van der Heide <info@jield.nl>"
LABEL org.opencontainers.image.source="https://github.com/jield-webdev/docker-repos"
LABEL org.opencontainers.image.description="Development MySQL Docker container"

COPY .docker/mysql/my.cnf /etc/mysql/conf.d/my.cnf