name: PHP 8.2 Worker

on:
  push:
    branches:
      - main

jobs:
  build-amd64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push (amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./php82-worker/Dockerfile # Use this format so we have access to the scripts folder
          platforms: linux/amd64
          push: true
          tags: ghcr.io/jield-webdev/docker-repos/php8.2-worker:latest

  build-arm64:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push (arm64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./php82-worker/Dockerfile # Use this format so we have access to the scripts folder
          platforms: linux/arm64
          push: true
          tags: ghcr.io/jield-webdev/docker-repos/php8.2-worker:arm64