name: PHP 8.4 FPM (dev)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-amd64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push linux/amd64
        uses: docker/build-push-action@v6
        with:
          context: ./php84-fpm-dev
          platforms: linux/amd64
          push: true
          tags: ghcr.io/jield-webdev/docker-repos/php8.4-fpm:dev

  build-arm64:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push linux/arm64
        uses: docker/build-push-action@v6
        with:
          context: ./php84-fpm-dev
          platforms: linux/arm64
          push: true
          tags: ghcr.io/jield-webdev/docker-repos/php8.4-fpm:arm64