name: PHP 8.6 Images

on:
  push:
    branches:
      - develop

jobs:
  cli-dev:
    uses: ./.github/workflows/docker-build-reusable.yml
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
    with:
      image_name: php8.6-cli
      context: .
      dockerfile: ./dockerfiles/php-cli-dev.Dockerfile
      tags: |
        ghcr.io/jield-webdev/docker-repos/php8.6-cli:dev
        ghcr.io/jield-webdev/docker-repos/php8.6-cli:dev-${{ github.sha }}
      build_args: |
        PHP_VERSION=8.6.0alpha1

  fpm-dev:
    uses: ./.github/workflows/docker-build-reusable.yml
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
    with:
      image_name: php8.6-fpm
      context: .
      dockerfile: ./dockerfiles/php-fpm-dev.Dockerfile
      tags: |
        ghcr.io/jield-webdev/docker-repos/php8.6-fpm:dev
        ghcr.io/jield-webdev/docker-repos/php8.6-fpm:dev-${{ github.sha }}
      build_args: |
        PHP_VERSION=8.6.0alpha1

  nginx-azure:
    uses: ./.github/workflows/docker-build-reusable.yml
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
    with:
      image_name: php8.6-nginx-azure
      context: .
      dockerfile: ./dockerfiles/php-nginx-azure.Dockerfile
      tags: |
        ghcr.io/jield-webdev/docker-repos/php8.6-nginx-azure:latest
        ghcr.io/jield-webdev/docker-repos/php8.6-nginx-azure:${{ github.sha }}
      build_args: |
        PHP_VERSION=8.6.0alpha1

  worker:
    uses: ./.github/workflows/docker-build-reusable.yml
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
    with:
      image_name: php8.6-worker
      context: .
      dockerfile: ./dockerfiles/php-worker.Dockerfile
      tags: |
        ghcr.io/jield-webdev/docker-repos/php8.6-worker:latest
        ghcr.io/jield-webdev/docker-repos/php8.6-worker:${{ github.sha }}
      build_args: |
        PHP_VERSION=8.6.0alpha1
